[build]
  publish = "."

# Redirect Netlify subdomain to custom domain
[[redirects]]
  from = "https://secvisiontech.netlify.app/*"
  to = "https://www.secvisiontech.com/:splat"
  status = 301
  force = true
